### ISSUE TITLE
Add guides about ros2 console-logging

### ISSUE THREAD

**Issue by alanmengg** [autowarefoundation/autoware-documentation#212]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Writing guidelines about ros2 console-logging.

### Purpose

Current console-logging.md in autowarefoundation/autoware-documentation/tree/main/docs/contributing/coding-guidelines/ros-nodes is empty.

### Possible approaches

Writing guidelines in  console-logging.md

### Definition of done

finisih writing

**Comment by alanmengg** [comment]
> @alanmengg Sorry for the inconvenience. Do you have any ideas about the guidelines?

I think I can write some basic usage case using autoware examples~

**Comment by kenji-miyake** [comment]
Oh, it's great! In that case, let's discuss it on your PR.

Today I found a PR that should be mentioned in the logging guideline. cc @takayuki5168 
https://github.com/autowarefoundation/autoware.universe/pull/2056
