### ISSUE TITLE
Create documentation for creating point cloud and hd/vector maps

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/autoware-documentation#32]
Follow up from: https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/1178

Add some brief documentation on how to create
- [x] point cloud maps
- [x] hd/vector maps

**Comment by LalithVipulananthan** [comment]
@xmfcx Hi Fatih. When you have time, could you have a look at the documentation that @n-patiphon created to see if it covers the criteria for this issue please?

https://autowarefoundation.github.io/autoware-documentation/main/how-to-guides/how-to-create-maps-for-autoware/

**Comment by xmfcx** [comment]
@LalithVipulananthan it covers it, thanks for reminding.

@n-patiphon thanks for your work!
