### ISSUE TITLE
Add documentation for Creating vehicle and sensor description

### ISSUE THREAD

**Issue by Naophis** [autowarefoundation/autoware-documentation#396]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [x] I've agreed with the maintainers that I can plan this task.

### Description

[Creating vehilce and sensor description](https://autowarefoundation.github.io/autoware-documentation/main/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-description/creating-vehicle-and-sensor-description/) is empty,  I'm going to add document it.

### Purpose

Adding specific instructions for creating vehicle and sensor descriptions.

### Possible approaches

The following three explanations.
* Description of vehicle_description configuration.
* Description of sensor_description configuration.
* Description of individual_parameter, how to be used in sensor_description.

### Definition of done

write document and merge it.

**Comment by Naophis** [comment]
@kenji-miyake @mitsudome-r 
May I add to the document with this direction?

**Comment by kenji-miyake** [comment]
@Naophis Of course, thank you!
