### ISSUE TITLE
Broken Links Issue Tracking

### ISSUE THREAD

**Issue by danielsanchezaran** [autowarefoundation/autoware-documentation#470]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Create a tracking issue for broken links on the Autoware Documentation.

### Purpose

Keep all broken link issues in a single place for easy tracking.

### Possible approaches

Report broken links and, if possible, what is the correct link.

### Definition of done

N/A

**Comment by danielsanchezaran** [comment]
This link for the planning simulator [shown here]( https://autowarefoundation.github.io/autoware-documentation/main/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-description/creating-vehicle-and-sensor-description/#4-simulator_modelparamyaml) is dead. I am not sure where it is supposed to point to.

**Comment by HansRobo** [comment]
A new pull-request for broken link by @isamu-takagi 
#503

**Comment by idorobotics** [comment]
Fixed by #503
