### ISSUE TITLE
Add documentation how to train traffic light fine detector model 

### ISSUE THREAD

**Issue by lexavtanke** [autowarefoundation/autoware-documentation#488]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Write instruction how to train traffic light detection models and prepare them for the inference in the autoware.  

 - [ ] https://github.com/autowarefoundation/autoware.universe/pull/5704
 - [ ] create a repo for training script and configs
 - [x] provide [sample dataset](https://autoware-files.s3.us-west-2.amazonaws.com/dataset/traffic_light_detection_sample_dataset.tar.gz)
 - [ ] [update [autoware.documentation page](https://autowarefoundation.github.io/autoware-documentation/main/how-to-guides/training-machine-learning-models/training-models/) ](https://github.com/autowarefoundation/autoware-documentation/pull/489)

### Purpose

Provide autoware users ability to easily train traffic light detector models with their own data specific to their case or area.

### Possible approaches

Create separate lightweight helping repo with the training scripts and configuration files based of mmdetection v2.28.2 (as used in TierIV internal usage). 
Write instructions how to properly prepare dataset for the task, how to prepare env for training, how to run training,  how to convert model to onnx. 

### Definition of done

Training documentation, conversion script and sample dataset are provided.

**Comment by vividf** [comment]
@lexavtanke Kindly ask what is the status of this one
