### ISSUE TITLE
Revisit documentation tree structure for more usability

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware-documentation#5]
Seeing the current [Autoware.Auto's documentation](https://autowarefoundation.gitlab.io/autoware.auto/AutowareAuto/), some information is dispersed and some information is unnecessary.

![image](https://user-images.githubusercontent.com/31987104/146961547-49936966-8724-4282-a8ee-ccbc5d6b6f96.png)

It should be refined so that people can easily access the information they want with no confusion.

This issue addresses the tree structure and we'll consider each content in #6.

**Comment by kenji-miyake** [comment]
I'd like to re-organize this into like this.

- Introduction
  - About Autoware
  - About this documentation
- Installation
  - Supported platforms
  - Installation of Autoware
    - Local
    - Docker
  - Installation of tools for users
  - Installation of tools for developers
- Tutorials
  - Planning simulation
  - Log data simulation
  - E2E simulation
  - Scenario testing
- How-to guides
  - Integration
    - Hardware setup
      - Vehicle setup
      - ECU setup
      - Sensors setup
    - Software setup
      - Customizing
      - Tuning
      - Map creation
  - Write a node
  - How to debug
  - etc.
- Design
  - Overview
  - Component interfaces
  - AD API
  - Repository structure
  - Development process
  - Release process
- Contributing
  - Overview
    - License / code of conduct
    - Contribution workflow
  - Coding guidelines
    - Specific languages
      - C++
      - Python
      - etc.
    - ROS node design
      - topic namespace
      - launch
      - parameter
      - console logging
      - etc.
  - Testing guidelines
  - Documentation guidelines
  - Pull request guidelines
- Help
  - Support guidelines
  - Links to related documents

**Comment by kenji-miyake** [comment]
We'll create an empty tree like the above and consider each content in #6.

**Comment by kenji-miyake** [comment]
Related: https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/1178

**Comment by mitsudome-r** [comment]
From: https://gitlab.com/autowarefoundation/autoware-foundation/-/issues/192
  * For Tuning section, we should think of a way of describing tuning instruction in design document of each package and the Tuning guide in autoware-documention should be a collection of links to the package instruction. Same for customization. 
  * We don't want to have these documents heavily dependent on implementation since it is difficult to keep documents up-to-date while we do the development.
