### ISSUE TITLE
Documentation showing how to uninstall Autoware.Auto

### ISSUE THREAD

**Issue by BonoloAWF** [autowarefoundation/autoware-documentation#56]
## Description
Documentation should be updated to include a section explaining how to uninstall Autoware.Auto (and unnecessary dependencies).

## Steps Required
- [ ] Guide to uninstall Autoware.Auto from source 
- [ ] Guide to uninstall Autoware.Auto from ade

**Comment by kenji-miyake** [comment]
I feel it's enough to write the steps in Autoware.Auto's documentation or a thread of GitHub Discussions.
I don't want to add this to autoware-documentation since it would be noisy.

**Comment by BonoloAWF** [comment]
Makes sense. As long as the instructions are available somewhere in case people ask.
